trigger:
- main  # Defina aqui o nome do branch que acionará o pipeline

pool:
  vmImage: 'windows-latest'  # ou 'ubuntu-latest' dependendo do ambiente

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.x'
      displayName: 'Use .NET SDK 3.x'

    - script: dotnet restore
      displayName: 'Restore NuGet Packages'

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'Build Solution'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/path/to/artifacts'
        artifactName: 'drop'
      displayName: 'Publish Artifacts'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'NomeDaSuaAssinatura'
        appName: 'SeuServicoDeAplicativo'
        package: '$(System.ArtifactsDirectory)/drop/*.zip'
        deploymentMethod: 'zipDeploy'
      displayName: 'Deploy to Azure Web App'

